export enum RoleCode {
  ADMIN = "ADMIN", // Acceso a todo 
  SUPER_ADMIN = "SUPER_ADMIN", // Acceso a todo 
  WAREHOUSEMAN = "WAREHOUSEMAN", //DASHBOARD, PROVEEDORES Y CONFIGURACIÓN
  AUDITOR = "AUDITOR", // DASHBOARD, REPORTES Y CONFIGURACIÓN
  SELLER =  "SELLER" // DASHBOARD, VENTAS Y CONFIGURACIÓN
}

